### ISSUE TITLE
Dipswitches fails

### ISSUE THREAD

**Issue by yavimaya** [MiSTer-devel/Arcade-SNK_TripleZ80_MiSTer#1]
If you modify dip switches, image flashes and gets full of garbled graphics. 
There also you can't modify COINAGE if you set it to 1Co/6Cr

**Comment by RndMnkIII** [comment]
The dip switches weren't designed in real hardware to be operated while the machine is powered on. Apply a reset after a dip switch change and the core will restore normal operation. Check the new update that fixes MRA.

**Comment by yavimaya** [comment]
Now it is solved :)
