### ISSUE TITLE
Add support for the GRS Super Joystick 

### ISSUE THREAD

**Issue by MrWatusi** [MiSTer-devel/Arcade-SNK_TripleZ80_MiSTer#4]
It would be awesome to play the rotary games supported by this core using the proper control scheme.

https://thunderstickstudio.com/products/grs-super-joystick-ikari-warriors-limited-edition-international

**Comment by grupoleon** [comment]
would also like 2nd this request.  Playing ikari warriors with this proper control joystick would be greatly appreciated.

**Comment by RndMnkIII** [comment]
Having the manufacturer or a user lend me a unit so I could do tests would be an important step towards this. Unfortunately, as an amateur developer, I do not have an income level that allows me to purchase all types of peripherals for such specific uses.

**Comment by grupoleon** [comment]
Would love to, and can help with that.  Can you PM?

**Comment by grupoleon** [comment]
Nvmd.  saw your email.  sent you a message.

**Comment by grupoleon** [comment]
@RndMnkIII hoping you saw my email.

**Comment by RndMnkIII** [comment]
Hi, you can Contact me on Twitter,Telegram or Discord, search for @RndMnkIII

**Comment by grupoleon** [comment]
@RndMnkIII added you on discord.

**Comment by RndMnkIII** [comment]
The GRS Super Joystick support is going on.

**Comment by MrWatusi** [comment]
Awesome! Happy to help test if needed :)

**Comment by RndMnkIII** [comment]
I will add to official Mister FPGA Github repo, stay tuned! I need to add some comments about how to config the GRS Superjoystick

**Comment by RndMnkIII** [comment]
updated Ikari Warriors core:
https://github.com/MiSTer-devel/Arcade-IkariWarriors_MiSTer/tree/main/releases

**Comment by RndMnkIII** [comment]
added also GRS support to TNKIII core:
https://github.com/MiSTer-devel/Arcade-TNKIII_MiSTer
